data:
  video_name: ["FDP", "FDS","LM","Extensor"]
  batch_size: 16
  num_workers: 4

model:
  input_ch: 3
  hidden_dim: 256
  output_dim: 8

train:
  device: "cuda"       
  lr: 1e-4
  weight_decay: 0.0001
  epochs: 20

eval:
  checkpoint: "checkpoints/epoch_30.pt"